package report

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/apophis-eng/apophis/internal/models"
)

type Generator struct {
	OutputDir string
}

func New(outputDir string) *Generator {
	return &Generator{OutputDir: outputDir}
}

func (g *Generator) Write(r *models.Report) error {
	if err := os.MkdirAll(g.OutputDir, 0755); err != nil {
		return err
	}
	ts := r.GeneratedAt.Format("20060102-150405")
	base := fmt.Sprintf("%s/apophis-%s", g.OutputDir, ts)

	if err := writeJSON(base+".json", r); err != nil {
		return err
	}
	if err := writeMarkdown(base+".md", r); err != nil {
		return err
	}
	fmt.Printf("\n  reports written to:\n    - %s.json\n    - %s.md\n\n", base, base)
	return nil
}

func writeJSON(path string, r *models.Report) error {
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0644)
}

func writeMarkdown(path string, r *models.Report) error {
	var b strings.Builder

	b.WriteString("# APOPHIS — Vulnerability Assessment Report\n\n")
	b.WriteString(fmt.Sprintf("**Target:** `%s`\n", r.Target.Host))
	if r.Target.URL != "" {
		b.WriteString(fmt.Sprintf("**URL:** `%s`\n", r.Target.URL))
	}
	b.WriteString(fmt.Sprintf("**Generated:** %s\n", r.GeneratedAt.Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("**Duration:** %s\n", r.Duration))
	b.WriteString(fmt.Sprintf("**Parallel agents:** %d\n\n", r.Workers))

	b.WriteString("## Executive Summary\n\n")
	b.WriteString(fmt.Sprintf("- **Risk score:** `%d`\n", r.Summary.RiskScore))
	b.WriteString(fmt.Sprintf("- **Total findings:** %d\n", r.Summary.Total))
	b.WriteString(fmt.Sprintf("- 🔴 **CRITICAL:** %d\n", r.Summary.Critical))
	b.WriteString(fmt.Sprintf("- 🟠 **HIGH:** %d\n", r.Summary.High))
	b.WriteString(fmt.Sprintf("- 🟡 **MEDIUM:** %d\n", r.Summary.Medium))
	b.WriteString(fmt.Sprintf("- 🔵 **LOW:** %d\n", r.Summary.Low))
	b.WriteString(fmt.Sprintf("- ⚪ **INFO:** %d\n\n", r.Summary.Info))

	b.WriteString("### Severity Distribution\n\n")
	b.WriteString("```\n")
	b.WriteString(renderSeverityBar(r.Summary))
	b.WriteString("\n```\n\n")

	if len(r.PortScan) > 0 {
		b.WriteString("## Open Ports\n\n")
		b.WriteString("| Port | Service | Banner | Version |\n")
		b.WriteString("|------|---------|--------|---------|\n")
		for _, p := range r.PortScan {
			b.WriteString(fmt.Sprintf("| %d | %s | %s | %s |\n", p.Port, p.Service, truncate(p.Banner, 60), p.Version))
		}
		b.WriteString("\n")
	}

	if len(r.HTTPDiscovery) > 0 {
		b.WriteString("## HTTP Discovery\n\n")
		b.WriteString("| URL | Status | Server | Title |\n")
		b.WriteString("|-----|--------|--------|-------|\n")
		for _, h := range r.HTTPDiscovery {
			b.WriteString(fmt.Sprintf("| %s | %d | %s | %s |\n", h.URL, h.StatusCode, h.Server, truncate(h.Title, 50)))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Findings\n\n")
	if len(r.Findings) == 0 {
		b.WriteString("_No vulnerabilities detected._\n\n")
	} else {
		for i, f := range r.Findings {
			b.WriteString(renderFinding(i+1, f))
		}
	}

	b.WriteString("---\n\n")
	b.WriteString("_Generated by **APOPHIS** — vulnerability chaos engine. Use only against systems you own or are explicitly authorized to test._\n")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func renderSeverityBar(s models.Summary) string {
	if s.Total == 0 {
		return "  (no findings)"
	}
	width := 50
	parts := []struct {
		label string
		count int
		fill  string
	}{
		{"CRIT", s.Critical, "█"},
		{"HIGH", s.High, "▓"},
		{"MED ", s.Medium, "▒"},
		{"LOW ", s.Low, "░"},
		{"INFO", s.Info, "·"},
	}
	var bar strings.Builder
	for _, p := range parts {
		if p.count == 0 {
			continue
		}
		n := (p.count * width) / s.Total
		if n == 0 {
			n = 1
		}
		bar.WriteString(fmt.Sprintf("%s %s %d\n", p.label, strings.Repeat(p.fill, n), p.count))
	}
	return bar.String()
}

func renderFinding(i int, f models.Finding) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("### %d. [%s] %s\n\n", i, f.Severity, f.Title))
	if len(f.CVE) > 0 {
		b.WriteString(fmt.Sprintf("**CVE:** %s  \n", strings.Join(f.CVE, ", ")))
	}
	if f.CVSS > 0 {
		b.WriteString(fmt.Sprintf("**CVSS:** %.1f  \n", f.CVSS))
	}
	b.WriteString(fmt.Sprintf("**Category:** %s  \n", f.Category))
	b.WriteString(fmt.Sprintf("**Target:** `%s`", f.Target))
	if f.Port > 0 {
		b.WriteString(fmt.Sprintf(":%d", f.Port))
	}
	b.WriteString("  \n")
	b.WriteString(fmt.Sprintf("**Detected by:** `%s` (%s)  \n\n", f.WorkerID, f.Strategy))

	b.WriteString("**Description**\n\n")
	b.WriteString(f.Description + "\n\n")

	if f.Evidence != "" {
		b.WriteString("**Evidence**\n\n```\n" + f.Evidence + "\n```\n\n")
	}

	b.WriteString("**Exploitation**\n\n```\n" + f.Exploit + "\n```\n\n")
	b.WriteString("**Remediation**\n\n" + f.Remediation + "\n\n")

	if len(f.References) > 0 {
		b.WriteString("**References**\n\n")
		for _, ref := range f.References {
			if strings.HasPrefix(ref, "http") {
				b.WriteString(fmt.Sprintf("- %s\n", ref))
			} else {
				b.WriteString(fmt.Sprintf("- _%s_\n", ref))
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n\n")
	return b.String()
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
