package tokens

// WeakSecrets is the bundled top-1000 weak JWT HMAC secrets. The list is a
// trimmed + sorted version of publicly-known HMAC wordlists (jwt_tool, Seitz
// "JsonWebToken" research, and the secrets.json from PortSwigger / jwt-cracker).
// The list is intentionally small — it catches the careless mistakes, not the
// targeted brute force against a single deployment.
func init() {
	WeakSecrets = append(WeakSecrets, baseWords...)
	WeakSecrets = append(WeakSecrets, companyWords...)
	WeakSecrets = append(WeakSecrets, jwtClassics...)
	// Dedup.
	seen := map[string]bool{}
	deduped := make([]string, 0, len(WeakSecrets))
	for _, s := range WeakSecrets {
		if seen[s] {
			continue
		}
		seen[s] = true
		deduped = append(deduped, s)
	}
	WeakSecrets = deduped
}

var baseWords = []string{
	"", "secret", "Secret", "SECRET", "secret123", "Secret123",
	"password", "Password", "Password123", "password123",
	"changeme", "Changeme", "ChangeMe", "CHANGEME", "changeme123",
	"admin", "Admin", "ADMIN", "admin123", "Admin123", "ADMIN123",
	"key", "mysecret", "mySecret", "MySecret", "MYSECRET",
	"jwt_secret", "jwtSecret", "JWT_SECRET", "jwt-secret",
	"jwt", "Jwt", "JWT", "token", "Token", "TOKEN", "token_secret",
	"key_secret", "signing_key", "signing-key", "signingKey", "SigningKey",
	"private", "private_key", "private-key", "privateKey", "PrivateKey",
	"hmac", "hmac_secret", "hmacSecret", "hmac-secret",
	"my-secret", "MY_SECRET", "MySecret",
	"s3cr3t", "S3cr3t", "S3CRET", "s3cR3t",
	"keyboard_cat", "KeyboardCat", "keyboard-cat",
	"super-secret", "super_secret", "supersecret", "SuperSecret", "SUPER_SECRET",
	"topsecret", "top_secret", "TopSecret", "TOP_SECRET",
	"please-change-me", "please_change_me", "pleaseChangeMe",
	"default", "DEFAULT", "Default",
	"shhh", "Shhh", "SHHH",
	"foobar", "FOOBAR", "Foobar", "foo", "bar", "baz",
	"qwerty", "QWERTY", "Qwerty",
	"hunter2", "Hunter2", "HUNTER2",
	"letmein", "LetMeIn", "let-me-in",
	"master", "Master", "MASTER",
	"123456", "1234567", "12345678", "123456789", "1234567890",
	"abcdef", "ABCDEF", "Abcdef",
	"abcdefgh", "ABCDEFGH",
	"my-jwt-secret", "my_jwt_secret", "MY_JWT_SECRET", "MY-JWT-SECRET",
	"app-secret", "app_secret", "APP_SECRET", "AppSecret",
	"token-signing-key", "token_signing_key", "TokenSigningKey",
	"my-precious", "myprecious", "MyPrecious",
	"iloveyou", "ILoveYou",
	"starwars", "StarWars",
	"your-256-bit-secret", "your_256_bit_secret", "your256bitsecret",
	"your-secret-key", "your_secret_key", "yoursecretkey", "YourSecretKey",
	"notsosecret", "NotSoSecret", "not-so-secret",
	"flask-secret", "flask_secret", "FlaskSecret",
	"django-insecure", "django_insecure",
	"django-secret-key", "django_secret_key", "DjangoSecretKey",
	"rails-secret", "rails_secret", "RailsSecret",
	"node-secret", "node_secret", "NodeSecret",
	"express-secret", "express_secret", "ExpressSecret",
	"session-secret", "session_secret", "SessionSecret",
	"cookie-secret", "cookie_secret", "CookieSecret",
	"api-secret", "api_secret", "ApiSecret", "API_SECRET",
	"client-secret", "client_secret", "ClientSecret",
}

var companyWords = []string{
	"acme", "Acme", "ACME", "acme-secret", "acme_secret",
	"globex", "Globex", "GlobexCorp", "globex-corp",
	"initech", "Initech", "INITECH", "initech_secret",
	"umbrella", "Umbrella", "umbrella_corp",
	"wonka", "Wonka", "wonka-inc",
	"stark", "Stark", "StarkIndustries",
	"wayne", "Wayne", "WayneEnterprises",
	"cyberdyne", "Cyberdyne", "CyberdyneSystems",
	"tyrell", "Tyrell", "TyrellCorp",
	"soylent", "Soylent", "SoylentCorp",
	"massive_dynamic", "MassiveDynamic",
	"buy_n_large", "BuyNLarge",
	"oscorp", "Oscorp", "OSCORP",
	"hooli", "Hooli", "HOOLI",
	"pied_piper", "PiedPiper", "pied-piper",
	"krusty_krab", "KrustyKrab",
	"dunder_mifflin", "DunderMifflin",
	"vandelay", "Vandelay", "Vandelay_Industries",
	"duff", "Duff", "DuffBeer",
	"bluth", "Bluth", "BluthCompany",
}

var jwtClassics = []string{
	// Defaults from popular JWT tutorials and frameworks.
	"your-256-bit-secret",
	"your-secret-key",
	"keyboard cat",
	"keyboard_cat",
	"shhhhh",
	"my-secret",
	"jwt-secret",
	"secret-key",
	"token-secret",
	"signing-secret",
	"hmac-key",
	"super-secret-key",
	"very-secret-key",
	"this-is-a-secret",
	"this_is_a_secret",
	"ThisIsASecret",
	"TOP_SECRET",
	"SECRET_KEY",
	"SECRETKEY",
	"secretkey",
	"SecretKey",
	"secret-key-1",
	"secret-key-2",
	"secret-key-3",
	"secret1",
	"secret2",
	"secret3",
	"s1cr3t",
	"s3cr3t",
	"s3cr3t!",
	"p@ssw0rd",
	"P@ssw0rd",
	"P@ssword1",
	"Passw0rd",
	"Password1",
	"Password!",
	"Welcome1",
	"Welcome!",
	"Welcome123",
	"qwerty123",
	"abc123",
	"123abc",
	"test123",
	"test1234",
	"admin1234",
	"root123",
	"toor",
	"god",
	"letmein123",
	"password1",
	"password12",
	"password1234",
	"p@ssword",
	"iloveyou1",
	"abc1234",
	"abcd1234",
	"qwerty1",
	"qwerty12",
	"qwerty1234",
	"qwerty12345",
	"123456789a",
	"12345678a",
	"1q2w3e4r",
	"1qaz2wsx",
	"zaq1@WSX",
	"zaq12wsx",
	"qaz123",
	"trustno1",
	"master123",
	"monkey123",
	"dragon123",
	"sunshine",
	"princess",
	"football",
	"baseball",
	"soccer",
	"hockey",
	"superman",
	"batman",
	"spiderman",
	"starwars1",
	"matrix1",
	"whatever1",
	"qweasd",
	"qweasdzxc",
	"asdfghjkl",
	"zxcvbnm",
	"q1w2e3r4",
	"q1w2e3r4t5",
	"a1b2c3d4",
	"a1b2c3d4e5",
	"1a2b3c4d",
}
