package research

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/apophis-eng/apophis/internal/tools/cve/dynamic"
)

// Generator emits Go source code that augments the static CVE database with
// runtime check stubs for new vulnerabilities discovered by the research agent.
// The generated code can be compiled into the binary on the next build.
type Generator struct {
	OutDir string
}

func NewGenerator(outDir string) *Generator {
	return &Generator{OutDir: outDir}
}

const genPackage = `// Code generated by apophis-research — DO NOT EDIT.
// Source: research agent sync on {{.GeneratedAt}}
// CVE count: {{.Count}}
//
// To bake these CVEs into the binary, copy this file to
// internal/tools/cve/dynamic/baked.go and rebuild. The init() function
// registers all entries into the dynamic store on first Open().

package dynamic

import "time"

var baked []Entry

func init() {
	baked = []Entry{
{{- range .Entries}}
		{
			CVE:         {{printf "%q" .CVE}},
			Service:     {{printf "%q" .Service}},
			Version:     {{printf "%q" .Version}},
			Severity:    {{printf "%q" .Severity}},
			CVSS:        {{printf "%.1f" .CVSS}},
			Title:       {{printf "%q" .Title}},
			Description: {{printf "%q" .Description}},
			Exploit:     {{printf "%q" .Exploit}},
			Remediation: {{printf "%q" .Remediation}},
			References:  []string{ {{- range .References}}{{printf "%q" .}},{{end}} },
			Source:      {{printf "%q" .Source}},
			Published:   time.Time{},
			HasKEV:      {{.HasKEV}},
		},
{{- end}}
	}
}
`

type genTemplate struct {
	GeneratedAt string
	Count       int
	Entries     []dynamic.Entry
}

func (g *Generator) Generate(entries []dynamic.Entry) (string, error) {
	if err := os.MkdirAll(g.OutDir, 0755); err != nil {
		return "", err
	}
	tpl, err := template.New("gen").Parse(genPackage)
	if err != nil {
		return "", err
	}
	path := filepath.Join(g.OutDir, "generated.go")
	f, err := os.Create(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	tpl.Execute(f, genTemplate{
		GeneratedAt: time.Now().Format(time.RFC3339),
		Count:       len(entries),
		Entries:     entries,
	})
	return path, nil
}

// StubFor returns a ready-to-paste Go function body that matches the CVE
// against a banner/service/version triple. Useful when the user wants to
// commit a permanent check into the codebase.
func StubFor(e dynamic.Entry) string {
	header := fmt.Sprintf(`// check%s checks for %s (%s, CVSS %.1f).
// Generated by apophis-research. Wire it into the matcher in cve.go.
func check%s(service, version, banner string) []models.Finding {
	if !serviceMatches(%q, service) {
		return nil
	}
	if !versionMatches(%q, version, banner) {
		return nil
	}
	return []models.Finding{{
		Title:       %q,
		Severity:    models.Severity(%q),
		CVSS:        %.1f,
		Category:    "CVE",
		Target:      service,
		Description: %q,
		Exploit:     %q,
		Remediation: %q,
	}}
}
`,
		safeIdent(e.CVE), e.CVE, e.Title, e.CVSS,
		safeIdent(e.CVE),
		e.Service, e.Version,
		e.Title, e.Severity, e.CVSS,
		e.Description, e.Exploit, e.Remediation,
	)
	return header
}

func safeIdent(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	return s
}
